version: "3.6"

services:
  mfa_dbwriter:
    container_name: mfa_dbwriter
    build:
      context: .
    volumes:
      - ./../../:/home
    tty: true
    stdin_open: true

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./../../db:/home/db

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
