services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      MARIADB_USER: adminer
      MARIADB_PASSWORD: adminer
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./data:/db/data    

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    links:
      - db